config/routes.rb
Rails.application.routes.draw do

  devise_for :editors

  root to: "posts#index"

  resources :posts do
    resources :comments
  end

  match ':controller(/:action(/:id))', :via => [:get, :post]

end

app/models/category.rb
class Category < ActiveRecord::Base
	has_and_belongs_to_many :editors
	has_and_belongs_to_many :posts, dependent: :delete_all

	has_attached_file :image, styles: { large: "600x600", medium: "300x300>", thumb: "150x150"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/comment.rb
class Comment < ActiveRecord::Base
	belongs_to :post
	belongs_to :editor
end

app/models/editor.rb
class Editor < ActiveRecord::Base
  	# Include default devise modules. Others available are:
  	# :confirmable, :lockable, :timeoutable and :omniauthable
	devise :database_authenticatable, :registerable,
	     :recoverable, :rememberable, :trackable, :validatable
	has_many :comments
	has_many :posts
	has_and_belongs_to_many :categories

	has_attached_file :user_avatar, styles: { large: "600x600", medium: "300x300>", thumb: "150x150"}
	validates_attachment_content_type :user_avatar, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]
end

app/models/post.rb
class Post < ActiveRecord::Base
	validates :title, presence: true
	validates :content, presence: true
	validates :image, presence: true

	has_many :comments
	belongs_to :editor
	has_and_belongs_to_many :categories

	has_attached_file :image, styles: { large: "800x800", medium_card: "460x360", normal_card: "300x200>", small_card: "140x140>"}
	validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

	scope :posts_of_week, lambda {where(:created_at => 1.week.ago..Time.now)}
	scope :visible, lambda {where(:visible => true)}
	scope :recent, lambda {order("posts.created_at DESC")}

	scope :odd, lambda {where("id % 2 = ?", "0")}
	scope :even, lambda {where("id % 2 = ?", "1")}

	scope :most_liked, lambda {order("posts.likes_count DESC")}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  
  before_action :authenticate_editor!, except: [:show]

  layout 'default'
  
  def index
    @categories = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @new_category = Category.new()
  end

  def create
    @new_category = Category.new(category_params)

    if @new_category.save
      redirect_to(:action => 'index')
    else
      render('new')
    end
  end

  def edit
  end

  def update
  end

  def delete
  end

  private
  def category_params
    params.require(:category).permit(:name, :description, :image)
  end

end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  layout false
  
  def index
  end

  def show
  end

  def new
  end

  def create 
    @this_post = Post.find(params[:post_id])
    @new_comment = @this_post.comments.create(params.require(:comment).permit(:content))
    @new_comment.editor_id = 1;

    if @new_comment.save
      @this_post.comment_count = @this_post.comments.count
      @this_post.save 
      redirect_to @this_post
    end 
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/editors_controller.rb
class EditorsController < ApplicationController
  layout false
  
  def index
  end

  def show
  end

  def new
  end

  def create
    
  end

  def edit
  end

  def update
  end

  def delete
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_editor!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  layout 'default'

  def index
    @posts = Post.visible.recent
  end

  def give_me_posts (main_posts)
    main_posts.each do |post|
    post_category = post.categories.first
      render(:partial => "shared/default_card", :locals => {:post => post, :post_category => post_category})
    end
  end
  helper_method :give_me_posts

  def show
  end

  def new
    @post = Post.new()
  end

  def create
    @post = Post.new(post_params)

    #Attach an editor to the post
    post_editor = current_editor

    #Getting post category
    post_category = params[:post_category]

    if @post.save

      #Attach the editor and categories to the post
      post_editor.posts << @post
      @post.categories << Category.find(post_category)

      redirect_to post_path(@post)
    else
      render('new')
    end
  end

  def edit
  end

  def update
    #Getting post category
    post_category = params[:post_category]

    if @post.update(post_params)
      @post.categories.clear
      @post.categories << Category.find(post_category)

      redirect_to post_path(@post)
    else
      render('edit')
    end
  end

  def destroy
    @post.destroy
    redirect_to root_path
  end

  private
  def post_params
    params.require(:post).permit(:title, :content, :image, :post_categories)
  end

  def find_post
    @post = Post.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/editors_helper.rb
module EditorsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/categories/delete.html.erb
<h1>Categories#delete</h1>
<p>Find me in app/views/categories/delete.html.erb</p>

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/index.html.erb
<%= link_to("Add new Category",{:action => 'new'}) %>

<table>
	<tr>
		<th>&nbsp;</th>
		<th>Name</th>
		<th>Description</th>
		<th>Post Count</th>
		<th>Image</th>
	</tr>
	<% @categories.each do |category| %>
	<tr>
		<td>&nbsp;</td>
		<td><%= category.name %></td>
		<td><%= category.description %></td>
		<td><%= category.post_count %></td>
		<td><%= image_tag category.image.url(:thumb) %></td>
	</tr>
	<% end %>
</table>

app/views/categories/new.html.erb
<h1>Add New Category</h1>

<%= form_for(:category, :url => {:action => 'create'}, html: { multipart: true }) do |form| %>
	<%= form.text_field :name %>
	<%= form.text_field :description %>
	<%= form.file_field :image %>
	
	<%= form.submit %>
<% end %>

app/views/categories/show.html.erb
<%
  cat_posts = @category.posts.all
  sidebar_posts = Post.all.most_liked
%>

<div class=" row single-header">
  <%= image_tag(@category.image.url, :class => "bg-single food") %>
</div>

<div class="container">
  <div class="row col l12 m12 s12">
    <!-- MAIN CONTENT START -->
    <div class="col l9 m8 s12 main-content">
      <h5 class="h-sec"><i class="small material-icons">play_arrow</i>&nbsp;&nbsp;Hot Articles</h5>
      <div class="row">
          <%if cat_posts.count > 0
            #check if there are more posts
            cat_posts.each do |post|
            post_category = post.categories.first %>

            <%= render(:partial => "shared/default_card", :locals => {:post => post, :post_category => post_category}) %>

            <% end #loop end %>
          <% end #if end %>
      </div>
    </div>
    <!-- MAIN CONTENT END -->

    <!-- SIDEBAR START -->
    <div class="col l3 m4 s12 side-content">
      
      <%= render(:partial => "shared/social_media_sidebar") %>

      <div class="row hotest">
        <h5 class="h-sec"><i class="small material-icons">play_arrow</i>&nbsp;&nbsp;Hotest Articles</h5>

        <%if sidebar_posts.count > 0
          #check if there are more posts
          sidebar_posts.each do |post|
          post_category = post.categories.first %>

          <%= render(:partial => "shared/sidebar_card", :locals => {:post => post, :post_category => post_category}) %>

          <% end #loop end %>
        <% end #if end %>
      </div>

    </div>

    <!-- SIDEBAR END -->

  </div>
</div>

app/views/categories/update.html.erb
<h1>Categories#update</h1>
<p>Find me in app/views/categories/update.html.erb</p>

app/views/comments/delete.html.erb
<h1>Comments#delete</h1>
<p>Find me in app/views/comments/delete.html.erb</p>

app/views/comments/edit.html.erb
<h1>Comments#edit</h1>
<p>Find me in app/views/comments/edit.html.erb</p>

app/views/comments/index.html.erb
<h1>Comments#index</h1>
<p>Find me in app/views/comments/index.html.erb</p>

app/views/comments/new.html.erb
<h1>Comments#new</h1>
<p>Find me in app/views/comments/new.html.erb</p>

app/views/comments/show.html.erb
<h1>Comments#show</h1>
<p>Find me in app/views/comments/show.html.erb</p>

app/views/comments/update.html.erb
<h1>Comments#update</h1>
<p>Find me in app/views/comments/update.html.erb</p>

app/views/editors/delete.html.erb
<h1>Editors#delete</h1>
<p>Find me in app/views/editors/delete.html.erb</p>

app/views/editors/edit.html.erb
<h1>Editors#edit</h1>
<p>Find me in app/views/editors/edit.html.erb</p>

app/views/editors/index.html.erb
<h1>Editors#index</h1>
<p>Find me in app/views/editors/index.html.erb</p>

app/views/editors/new.html.erb
<h1>Editors#new</h1>
<p>Find me in app/views/editors/new.html.erb</p>

app/views/editors/show.html.erb
<h1>Editors#show</h1>
<p>Find me in app/views/editors/show.html.erb</p>

app/views/editors/update.html.erb
<h1>Editors#update</h1>
<p>Find me in app/views/editors/update.html.erb</p>

app/views/layouts/_footer.html.erb
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-74284320-1', 'auto');
  ga('send', 'pageview');

</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
	  <title>Viral And Fast</title>
	  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
	  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
	  <%= csrf_meta_tags %>
	</head>
	<body>

	<%= yield %>

	</body>
</html>

app/views/layouts/default.html.erb
<!DOCTYPE html>
  <html>
    <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
      <title>Viral And Fast</title>
      <meta name="description" content="">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <link rel="apple-touch-icon" href="apple-touch-icon.png">

      <!--Import Google Icon Font-->
      <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

      <!--Import ALL CSS-->
      <%= stylesheet_link_tag('application') %>

      <!--Let browser know website is optimized for mobile-->
      <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

      <%= favicon_link_tag 'favicon-96x96.png' %>

      <%= csrf_meta_tags %>
    </head>

    <body>

      <!-- Navigation Menu -->
      <nav class="navbar top-nav">
        <div class="nav-wrapper container">
          <ul id="nav-mobile" class="right">
            <li><a href="#">About us</a></li>
            <li><a href="#">Contact us</a>
              <ul>
                <li><a href="https://twitter.com/ViralAndFast"><i class="fa fa-facebook fa-2x"><span>Facebook</span></i></a></li>
                <li><a href="https://twitter.com/ViralAndFast"><i class="fa fa-twitter fa-2x"><span>Twitter</span></i></a></li>
                <li><a href="https://www.linkedin.com/company/viral-and-fast"><i class="fa fa-linkedin fa-2x"><span>LinkedIn</span></i></a></li>
              </ul>
            </li>
          </ul>
        </div>
      </nav>

      <nav class="main-menu">
        <div class="nav-wrapper container">
        <a href="#" data-activates="mobile-demo-2" class="button-collapse"><i class="material-icons">menu</i></a>
          <%= link_to image_tag('logo.png', :alt => 'logo'), {:controller => 'posts', :action => 'index'}, :class => "brand-logo" %>

          <ul id="nav-mobile" class="center right hide-on-med-and-down">
            <li><%= link_to("Home", {:controller => 'posts', :action => 'index'}) %></li>
            
            <% Category.all.each do |category| %>
            <li><%= link_to(category.name, {:controller => 'categories', :action => 'show', :id => category.id}) %></li>
            <% end %>

            <ul class="right sign-up">
              <!-- <li><a href="#"><i class="material-icons">search</i></a></li> -->
              <% if editor_signed_in? %>
                <li><%= link_to "Add Post", {:controller => 'posts', :action => 'new'} %></li>
              <% else %>
                <li><%= link_to "Sign In", {:controller => 'editors', :action => 'sign_in'} %></li>
              <% end %>
              
              <!-- <li><a href="#"><span>Sign up</span></a></li> -->
            </ul>

          </ul>

          <ul class="side-nav" id="mobile-demo-2">
            <li><%= link_to("Home", {:controller => 'posts', :action => 'index'}) %></li>
            
            <% Category.all.each do |category| %>
            <li><%= link_to(category.name, {:controller => 'categories', :action => 'show', :id => category.id}) %></li>
            <% end %>
            
            <!-- <li><a href="#"><i class="material-icons">search</i></a></li> -->
            <li><a href="#"><span>Sign in</span></a></li>
            <!-- <li><a href="#"><span>Sign up</span></a></li> -->
          </ul>
        </div>
      </nav>

      <!-- Put Ads here -->

      <!-- <div class="container ads">
        
      </div> -->

      <div class="container">
          <p class="notice"><%= notice %></p>
          <p class="alert"><%= alert %></p>
      </div>

      <%= yield %>

  	<footer>
  		<%= javascript_include_tag('application') %>
      <%= render 'layouts/footer' %>
	   </footer>
    </body>
  </html>

app/views/posts/delete.html.erb
<h1>Posts#delete</h1>
<p>Find me in app/views/posts/delete.html.erb</p>

app/views/posts/edit.html.erb
<div class="container" style="margin-bottom: 100px;">
	<h2>Edit Post</h2>

	<%= form_for(@post) do |form| %>
		<%= render :partial => "shared/form_post", :locals => {:form => form} %>
	<% end %>
</div>

app/views/posts/index.html.erb
<%
  slider_posts = @posts.limit(5)

  main_posts = @posts.offset(5)

  # represens the number of main blocks to be added in the main container
  blocks_counter = main_posts.count / 11

  sidebar_posts = @posts.most_liked
%>
      <% if slider_posts.count == 5 %>
      <!-- Slider Begins here! -->
      <div class="top-news row container">
        <div class="new-sec new-1 col l5 m12 s12">
          <div class="shadow"></div>
          <%= link_to image_tag(slider_posts[0].image.url(:large), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => slider_posts[0].id} %>

          <div class="caption left-align col l10 m8 s8">
            
            <a href="#"><h5 class="light grey-text text-lighten-3"><%= link_to(slider_posts[0].title, {:action => 'show', :id => slider_posts[0].id}) %></h5></a>
          </div>         
        </div>
        <div class="new-sec col l4 m12 s12">
          <div class="new-2 col l12 m6 s12">
            <div class="shadow"></div>
            <%= link_to image_tag(slider_posts[1].image.url(:medium_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => slider_posts[1].id} %>

            <div class="caption left-align col l9 m12 s9">
            
            <a href="#"><h5 class="light grey-text text-lighten-3"><%= link_to(slider_posts[1].title, {:action => 'show', :id => slider_posts[1].id}) %></h5></a>
            </div>        
          </div>
          <div class="new-3 col l12 m6 s12">
            <div class="shadow"></div>
            <%= link_to image_tag(slider_posts[2].image.url(:medium_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => slider_posts[2].id} %>

            <div class="caption left-align col l9 m12 s9">
              
            <a href="#"><h5 class="light grey-text text-lighten-3"><%= link_to(slider_posts[2].title, {:action => 'show', :id => slider_posts[2].id}) %></h5></a>
            </div>         
          </div>         
        </div>
        <div class="new-sec col l3 m12 s12">
          <div class="new-4 col l12 m6 s12">
            <div class="shadow"></div>
            <%= link_to image_tag(slider_posts[3].image.url(:medium_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => slider_posts[3].id} %>

            <div class="caption left-align col l12 m12 s9">
              
            <a href="#"><h5 class="light grey-text text-lighten-3"><%= link_to(slider_posts[3].title, {:action => 'show', :id => slider_posts[3].id}) %></h5></a>
            </div>         
          </div>
          <div class="new-5 col l12 m6 s12">
            <div class="shadow"></div>
            <%= link_to image_tag(slider_posts[4].image.url(:medium_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => slider_posts[4].id} %>
            <div class="caption left-align col l12 m12 s9">
              
            <a href="#"><h5 class="light grey-text text-lighten-3"><%= link_to(slider_posts[4].title, {:action => 'show', :id => slider_posts[4].id}) %></h5></a>
            </div>         
          </div>        
        </div>
      </div>
      <% end %>
      <!-- Slider End -->
      
      <div class="container">
        <div class="row col l12 m12 s12">
          <!-- MAIN CONTENT START -->
          <div class="col l9 m8 s12 main-content">
            
            <% blocks_counter.times do %>

            <% posts_arr = main_posts[0..10] %>
            <div class="row">
              <% 6.times do |i| 
                post_category = posts_arr[i].categories.first %>
                <%= render(:partial => "shared/default_card", :locals => {:post => posts_arr[i], :post_category => post_category}) %>
              <% end %>
            </div>

            <div class="row">
              <%= render(:partial => "shared/big_card", :locals => {:post => posts_arr[6], :post_category => posts_arr[6].categories.first}) %>
              <div class="col l6 m6 s12">
                <div class="videos">
                  <ul class="video-scroll">
                    <% 4.times do |i| 
                      post_category = posts_arr[i].categories.first %>
                      <%= render(:partial => "shared/small_card", :locals => {:post => posts_arr[i], :post_category => post_category}) %>
                    <% end %>
                  </ul>
                </div>
                <!-- end of videos div -->
              </div>
            </div>
            
            <% 11.times do |i| 
              main_posts.to_a.delete_at(i) 
              end %>

            <% end %>

          </div>

      
          <!-- MAIN CONTENT END -->

          <!-- SIDEBAR START -->
          <div class="col l3 m4 s12 side-content">
            
            <%= render(:partial => "shared/social_media_sidebar") %>

            <div class="row hotest">
              <h5 class="h-sec"><i class="small material-icons">play_arrow</i>&nbsp;&nbsp;Hotest Articles</h5>

              <%if sidebar_posts.count > 0
                #check if there are more posts
                sidebar_posts.each do |post|
                post_category = post.categories.first %>

                <%= render(:partial => "shared/sidebar_card", :locals => {:post => post, :post_category => post_category}) %>

                <% end #loop end %>
              <% end #if end %>
            </div>

          </div>

          <!-- SIDEBAR END -->

        </div>

        <%= render(:partial => "shared/modal_share") %>

app/views/posts/new.html.erb
<div class="container" style="margin-bottom: 100px;">
	<h2>Add New Post</h2>

	<%= form_for(:post, :url => {:action => 'create'}, html: { multipart: true }) do |form| %>
		<%= render :partial => "shared/form_post", :locals => {:form => form} %>
	<% end %>
</div>

app/views/posts/show.html.erb
<% sidebar_posts = Post.most_liked %>

      <div class="article container">
        
        <div class="row col l12 m12 s12">
          <div class="row col l8 m12 article left-section">

            <div class="row col l12 article-header">
              <h5 class="article-title"><%= @post.title %></h5>
              <a class="article-views" href="#"><i class="fa fa-eye"></i><%= Random.rand(10...42) %> Views</a>
              <a class="article-comments" href="#"><i class="fa fa-comment"></i><%= @post.comments.count %> Comments</a>
            </div>

            <% if @post.editor == current_editor %>
            <div class="row col l12 post-controllers">
              <%= link_to "Edit Post", {:action => 'edit', :id => @post.id}, :class => 'btn' %>
              <%= link_to( "Delete Post", post_path(@post), :class => 'btn', method: :delete, data: {confirm: 'Are you sure?'} ) %>
            </div>
            <% end %>

            <div class="col m12 share-row">

              <a href="http://www.facebook.com/sharer/sharer.php?u=<%= request.original_url %>" target="_blank" class="waves-effect waves-light btn face-btn"><i class="fa fa-facebook fa-2x"></i></a>
              
              <a href="http://twitter.com/share?url=<%= request.original_url %>&text=<%= @post.title %>via=<USERNAME>" target="_blank" class="waves-effect waves-light btn twitter-btn"><i class="fa fa-twitter fa-2x"></i></a>
              
              <a href="http://www.linkedin.com/shareArticle?url=<%= request.original_url %>&title=<%= @post.title %>&summary=<%= @post.title %>&source=<%= request.original_url %>" target="_blank" class="waves-effect waves-light btn linkedin-btn"><i class="fa fa-linkedin fa-2x"></i></a>
              
              <a href="https://plus.google.com/share?url=<%= request.original_url %>" target="_blank" class="waves-effect waves-light btn google-btn"><i class="fa fa-google-plus fa-2x"></i></a>
              
              <a href="http://www.stumbleupon.com/submit?url=<%= request.original_url %>&title=<%= @post.title %>" target="_blank" class="waves-effect waves-light btn stumbleupon-btn"><i class="fa fa-stumbleupon fa-2x"></i></a>
              
              <a href="http://reddit.com/submit?url=<%= request.original_url %>&title=<TITLE>" target="_blank" target="_blank" class="waves-effect waves-light btn reddit-btn"><i class="fa fa-reddit fa-2x"></i></a>

            </div>

            <div class="col m12">  
      
              <div class="article-content">
                <div class="article-text">
                  
                  <div class="fr-view">
                    <%= @post.content.html_safe %>
                  </div>

                </div>
              </div>
            
            </div>

            <div class="row col m11 discussion">
              <h6>DISCUSSION</h6>

              <% @post.comments.each do |comment| %>
              <div class="row disc">

                <div class="col s11">
                  <p class="black-text">
                  <%= comment.content %>
                  </p>
                </div>
              </div>
              <% end %>
            </div>

            <%= form_for(:comment, :url => {:controller => 'comments', :action => 'create', :post_id => @post.id}) do |f| %>
              
              <%= f.text_field(:content, :placeholder => "Add a comment") %>
              <%= submit_tag("Comment", :class => 'btn') %>

            <% end %>

          </div><!-- end of left section -->

          <!-- SIDEBAR START -->
          <div class="col l4 m4 article side-content">
            
            <%= render(:partial => "shared/social_media_sidebar") %>

            <div class="row hotest">
              <h5 class="h-sec"><i class="small material-icons">play_arrow</i>&nbsp;&nbsp;Hotest Articles</h5>

              <% if sidebar_posts.count > 0
                #check if there are more posts
                sidebar_posts.each do |post|
                post_category = post.categories.first %>

                <%= render(:partial => "shared/sidebar_card", :locals => {:post => post, :post_category => post_category}) %>

                <% end #loop end %>
              <% end #if end %>
            </div>

          </div>

          <!-- SIDEBAR END -->

        </div>

      </div>

      <%= render(:partial => "shared/modal_share") %>

app/views/posts/update.html.erb
<h1>Posts#update</h1>
<p>Find me in app/views/posts/update.html.erb</p>

app/views/shared/_big_card.html.erb
<div class="col l6 m6 s12">
  <!-- card -->
  <div class="card medium">
    <div class="shadow"></div>
    <div class="card-image">
      <%= link_to image_tag(post.image.url(:normal_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => post.id} %>
      <span class="card-section"><%= link_to(post_category.name, {:controller => 'categories', :action => 'show', :id => post_category.id}, :class => 'type') %></span>
      <a data-position="left" data-delay="0" data-tooltip="<%= post.likes_count %> likes" class="like-icon tooltipped" href="#"><i class="fa fa-heart-o"></i></a>
      <a data-position="left" data-delay="0" data-tooltip="share" class="share-icon tooltipped modal-trigger" href="#modal-share"><i class="fa fa-share-alt"></i></a>
      <a data-position="left" data-delay="0" data-tooltip="watch later" class="watch-icon tooltipped" href="#"><i class="fa fa-clock-o"></i></a>
      <a href="/posts/<%= post.id %>"><p class="card-title"><%= post.title %></p></a>
    </div>

    <div class="card-action">
      <a class="views" href="#"><i class="fa fa-eye"></i><%= Random.rand(100...1000) %> Views</a>
      <a class="comments" href="#"><i class="fa fa-comment"></i><%= post.comment_count %> Comments</a>
    </div>
  </div>
  <!-- end of card -->
</div>

app/views/shared/_default_card.html.erb
<!-- card -->
<div class="col l4 m4 s12">
  <div class="card small">
      <div class="card-image">
          <%= link_to image_tag(post.image.url(:normal_card), :class => "responsive-img"), {:controller => 'posts', :action => 'show', :id => post.id} %>
          <span class="card-section"><%= link_to(post_category.name, {:controller => 'categories', :action => 'show', :id => post_category.id}, :class => 'type') %></span>
          <a data-position="left" data-delay="0" data-tooltip="<%= post.likes_count %> likes" class="like-icon tooltipped" href="#"><i class="fa fa-heart-o"></i></a>
          <a data-position="left" data-delay="0" data-tooltip="share" class="share-icon tooltipped modal-trigger" href="#modal-share"><i class="fa fa-share-alt"></i></a>
          <a data-position="left" data-delay="0" data-tooltip="watch later" class="watch-icon tooltipped" href="#"><i class="fa fa-clock-o"></i></a>
      </div>
      <div class="card-content">
        <a href="/posts/<%= post.id %>"><p class="card-title"><%= post.title %></p></a>
      </div>
      <div class="card-action">
          <a class="views" href="#"><i class="fa fa-eye"></i><%= Random.rand(100...1000) %> Views</a>
          <a class="comments" href="#"><i class="fa fa-comment"></i><%= post.comment_count %> Comments</a>
          <!-- <a class="author" href="#"><i class="fa fa-user"></i>marie david</a> -->
      </div>
  </div>
</div>
<!-- end of card -->